language: android
notifications:
  email:
    recipients:
      - mrebollob@gmail.com
    on_success: change
    on_failure: always

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

jdk:
  - oraclejdk8

before_install:
  - ./travis-ci/setup.sh
  - chmod +x gradlew

android:
  components:
    - tools
    - build-tools-24.0.2
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./travis-ci/build.sh
  - ./gradlew checkstyle
  - ./gradlew test
  - ./gradlew build connectedCheck